# Frontend
FROM ubuntu:16.04

WORKDIR /mydir
RUN apt-get update && apt-get install -y curl git 

RUN curl -sL https://deb.nodesource.com/setup_10.x | bash
RUN apt-get install -y nodejs

RUN git clone https://github.com/docker-hy/frontend-example-docker.git

RUN cd  frontend-example-docker && npm install

RUN npm install -g serve

WORKDIR frontend-example-docker 

RUN node_modules/.bin/webpack --mode production

ENV API_URL=http://localhost:8000

RUN npm run build

ENTRYPOINT ["/usr/bin/serve", "-s", "-l","5000","dist"]


# Commands used

# docker run -it -p 3000:5000 frontend
# docker run -it -p 8000:8000 -v $(pwd)/logs.txt:/mydir/backend-example-docker/logs.txt backend


